name: video_monitoring_seventh
description: A Flutter project 
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  http: ^0.13.5
  shared_preferences: ^2.0.18
  video_player: ^2.6.0
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  equatable: ^2.0.5
  connectivity_plus: ^3.0.3
  fpdart: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1
  flutterando_analysis: ^0.0.2
  

flutter:
  uses-material-design: true
  assets:
    - assets/seventh_logo_white.png
